exp_name: "Augmentations_Concat_Independent"
output_dir: "./outputs/Augmentations_Concat/"
seed: 1234

data:
  sampling_rate: 16000
  label_map: {bonafide: 1, spoof: 0}

  train:
    dataset_type: "StandardDataset"
    dataset_names: ["Train"]
    parquet_files: ["/netscratch/yelkheir/DeepFense/DeepFense/train.parquet"]
    batch_size: 8 # Reduced batch size since we expand data 4x
    shuffle: True
    
    base_transform:
      - type: "pad"
        max_len: 64600

    augment_transform:
      - type: "augmentation_pipeline"
        mode: "sequential"       # Select K transforms
        k: 3                     # Pick 3 transforms
        execution: "independent" # Apply independently to copies (Branching)
        concat_original: True    # Stack with original -> [Original, Aug1, Aug2, Aug3]
        p: 1.0
        transforms:
          - type: "rawboost"
            noise_ratio: 1.0
          - type: "rir"
            noise_ratio: 1.0
            csv_file: "/netscratch/yelkheir/DeepFense/DeepFense/rirs.csv"
          - type: "add_noise"
            noise_ratio: 1.0
            csv_file: "/netscratch/yelkheir/DeepFense/DeepFense/rirs.csv"
          - type: "speed_perturb"
            noise_ratio: 1.0
            speeds: [90, 110]

  val:
    dataset_type: "StandardDataset"
    dataset_names: ["Val"]
    parquet_files: ["/netscratch/yelkheir/DeepFense/DeepFense/test.parquet"]
    batch_size: 16
    base_transform: [{type: "pad", max_len: 64600}]

model:
  type: "StandardDetector"
  frontend: 
    type: "wav2vec2" 
    args: 
      ckpt_path: "/netscratch/yelkheir/DeepFense/DeepFense/deepfense/models/pretrained/xlsr2_300m.pt"
      freeze: True
  backend: {type: "AASIST"}
  loss: [{type: "AMSoftmax", embedding_dim: 160, n_classes: 2, s: 32, m: 0.5}]

training:
  trainer: "StandardTrainer"
  epochs: 50
  device: "cuda"
  optimizer: {type: "adam", lr: 0.0001}

