exp_name: ASV5_wavlm_AASIST_NoAug_seed42
output_dir: ./outputs/batch6_ASV5/
seed: 42
data:
  sampling_rate: 16000
  label_map:
    bonafide: 1
    spoof: 0
  test:
    dataset_type: StandardDataset
    dataset_names: 
      - CustomTestDataset
    parquet_files: 
      - ./temp_audio/api_batch.parquet
    batch_size: 1
    shuffle: false
    num_workers: 1
    base_transform:
      - type: pad
        max_len: 64000
        pad_type: repeat
  train:
    dataset_type: StandardDataset
    parquet_files:
    - /netscratch/yelkheir/DeepFense/DeepFense/deepfense/config/parquets/ASV5/asvspoof5_train.parquet
    dataset_names:
    - ASV5_Train
    batch_size: 32
    shuffle: true
    num_workers: 4
    base_transform:
    - type: pad
      max_len: 64000
      random_pad: true
      pad_type: repeat
    augment_transform: []
  val:
    dataset_type: StandardDataset
    parquet_files:
    - /netscratch/yelkheir/DeepFense/DeepFense/deepfense/config/parquets/ASV5/asvspoof5_val.parquet
    dataset_names:
    - ASV5_Val
    batch_size: 32
    shuffle: false
    num_workers: 4
    base_transform:
    - type: pad
      max_len: 64000
      pad_type: repeat
model:
  type: StandardDetector
  frontend:
    type: wavlm
    args:
      ckpt_path: ./pretrained_models/WavLM-Large.pt
      freeze: false
      source: unil
  backend:
    type: AASIST
  loss:
  - type: "CrossEntropy"
    gamma: 2.0
    alpha: 0.25
    reduction: "mean"
    embedding_dim: 160
    n_classes: 2
    weight: 1.0
training:
  trainer: StandardTrainer
  epochs: 100
  early_stopping_patience: 7
  optimizer:
    type: adam
    lr: 1.0e-06
  metrics:
    ACC: {}
    EER: {}
  eval_every_epochs: 1
  device: cuda
  output_dir: ./outputs/batch6_ASV5/ASV5_wavlm_AASIST_NoAug_seed42_20260114_195522
